Add Draw Cone.
john-chapman/im3d pull request #60
Opened 2023-01-09 12:15 UTC by jiannanya

1.Add draw cone.
  2.Add draw cone filled.
  3.Add Imgui example for drawing cone.

2023-01-09 12:27 UTC, john-chapman commented on im3d.cpp
> +        if (!ctx.isVisible(_origin, _radius))
I think this should be the bounding sphere of the cone: `_origin + _normal * height / 2`, `height / 2`?

2023-01-09 12:28 UTC, john-chapman requested changes
Looks great! Just need to use the proper cone bounds for culling and detail estimation.

2023-01-09 12:56 UTC, jiannanya commented
Yeah,  I have fixed it for culling and detail estimation.

2023-01-09 12:57 UTC, jiannanya commented
> Looks great! Just need to use the proper cone bounds for culling and detail estimation.
Yeah, I have fixed it for culling and detail estimation.

2023-01-09 13:47 UTC, merged

2023-01-09 13:48 UTC, john-chapman commented
Great stuff - thanks for your contribution!

2025-09-14 11:48 UTC, john-chapman commented
FYI @jiannanya I've revisited the implementation of `DrawCone()` and `DrawConeFilled()` and made some changes to make the API more consistent with the other high order shape functions. I've also added separate start/end radii parameters for drawing truncated cones, and bool args for enabling the start/end caps when drawing the filled variants.

The old versions are still the default behavior to avoid API breaking changes, but are now deprecated. This is currently controlled via `IM3D_USE_DEPRECATED_DRAW_CONE` in [im3d_config.h](https://github.com/john-chapman/im3d/blob/master/im3d_config.h). 

See [the commit here](https://github.com/john-chapman/im3d/commit/3fd7afaf3192ed50bca29c191969aa41252b53d5).